apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: robo
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: t3.medium  #change to m5.large
    desiredCapacity: 2   # change to 2
    spot: true